# Generated by Django 3.0.7 on 2020-10-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(auto_created=True)),
                ('uemail', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=100)),
                ('upass', models.CharField(max_length=15)),
                ('admin', models.BooleanField()),
            ],
        ),
    ]
