# Generated by Django 3.0.7 on 2020-10-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='admin',
            field=models.CharField(max_length=7),
        ),
    ]
