# Generated by Django 3.0.7 on 2020-10-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20201023_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='uid',
        ),
    ]
